alertmanager:
  enabled: false

## Using default values from https://github.com/helm/charts/blob/master/stable/grafana/values.yaml
##
grafana:
  rbac:
    create: false
  serviceAccount:
    create: false

  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  adminPassword: password

kubelet:
  serviceMonitor:
    ## Enable scraping the kubelet over https. For requirements to enable this see
    ## https://github.com/coreos/prometheus-operator/issues/926
    ##
    https: false

coreDns:
  enabled: false

kube-state-metrics:
  rbac:
    create: false
  podSecurityPolicy:
    enabled: false

  resources:
    limits:
      cpu: 200m
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 512Mi


prometheus-node-exporter:
  serviceAccount:
    create: false
  rbac:
    create: false

prometheusOperator:
  serviceAccount:
    create: false

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 100Mi

prometheus:
  serviceAccount:
    create: false

  prometheusSpec:
    resources:
      requests:
        memory: 6Gi
        cpu: 1
      limits:
        memory: 8Gi
        cpu: 2

